name: flutter_hangman
description: Hangman Game

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: AmaticSC
      fonts:
        - asset: fonts/AmaticSC-Regular.ttf
        - asset: fonts/AmaticSC-Bold.ttf
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: Blinker
      fonts:
        - asset: fonts/Blinker-Regular.ttf
    - family: MiriamLibre
      fonts:
        - asset: fonts/MiriamLibre-Bold.ttf
        - asset: fonts/MiriamLibre-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf